---
- name: Installing apache2
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - apache2
    - libapache2-mod-php7.0

- name: Create user with home directory
  user: name={{ vsftpd.user }} password={{ vsftpd.password }} home={{ apache2.docroot }} shell=/usr/sbin/nologin

- name: Create vhost directory
  file: path={{ apache2.docroot }}/{{ item.site }} state=directory recurse=yes owner={{ vsftpd.user }} group={{ vsftpd.user }} mode=0775
  with_items:
    - "{{ sitename }}"

- name: Creating vhosts
  template: src=default.tpl dest=/etc/apache2/sites-available/{{ item.site }}.conf
  with_items:
     - "{{ sitename }}"
  notify: restart apache2

- name: Create logfile path directory
  file: path=/var/log/apache2/{{ item.site }} state=directory
  with_items:
    - "{{ sitename }}"

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify:
    - restart apache2

- name: Disable the default sites.
  command: a2dissite {{ item }}
  with_items:
    - 000-default.conf
    - default-ssl.conf

- name: a2ensite {{ item.site }}
  command: a2ensite {{ item.site }}
  args:
    creates: /etc/apache2/sites-enabled/{{ item.site }}.conf
  with_items:
    - "{{ sitename }}"
  notify:
    - restart apache2
