# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webserver', models.CharField(max_length=50)),
                ('documentroot', models.TextField(max_length=255)),
                ('sitecount', models.IntegerField()),
                ('sitename', models.TextField()),
                ('ftpserver', models.CharField(max_length=50)),
                ('ftpuser', models.CharField(max_length=60)),
                ('ftppassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='packages',
        ),
    ]
