# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore_app', '0002_auto_20170208_0237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ipaddress',
        ),
        migrations.AddField(
            model_name='webserver',
            name='ip_address',
            field=models.GenericIPAddressField(default='True'),
        ),
    ]
