# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore_app', '0003_auto_20170208_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webserver',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
